Repository WyriHaximus/github-action-get-previous-tag, pull requests merged in 2022-10, with the labels that each got.

#36 Use new way of outputting values from step/action
  main.js
Labels: JavaScript 🦏

#37 Bump to node16
  action.yml
Labels: YAML 🍄

#39 Use creatordate to fetch latest tag, as taggerdate does not sort properly
  main.js
Labels: JavaScript 🦏

#40 Remove newline characters from output
  main.js
Labels: JavaScript 🦏

#41 Drop \r from fallback
  main.js
Labels: bug, JavaScript 🦏
