Repository WyriHaximus/github-action-get-previous-tag, pull requests merged in 2024-01, with the labels that each got.

#52 Update to Node 20
  action.yml
Labels: YAML 🍄

#51 Add the ability to specify the working directory
  .github/workflows/ci.yml
  README.md
  action.yml
  main.js
Labels: JavaScript 🦏, YAML 🍄, Configuration ⚙, CI 🚧, MarkDown 📝

#44 Remove file removal action
  .github/workflows/ci.yml
Labels: YAML 🍄, Configuration ⚙, CI 🚧

#53 Stricten working directory tests
  .github/workflows/ci.yml
  main.js
Labels: JavaScript 🦏, YAML 🍄, Configuration ⚙, CI 🚧
